### PR TITLE
Merge QS-staging branch to master.

### PR DESCRIPTION
**Pull request by codezizo**
This updated the ML codelab to use AI Platform Notebook, upgraded to Python3 and fixed minor bugs.

### CODE REVIEW

**Comment by codezizo** [comment]
@pavertomato  can you please comment: "@googlebot I consent" to approve this pull request.

**Comment by pavertomato** [comment]
@googlebot I consent.

**Comment by codezizo** [comment]
@googlebot I fixed it.

**Comment by pavertomato** [comment]
seems like it squashed commits
may i'll create branch with single commit made by me?

**Comment by pavertomato** [comment]
yep, squashed commits have "878990+pavertomato@users.noreply.github.com" instead of my email with cla

**Comment by codezizo** [comment]
Yes that seems to be the problem! Try squashing commits and committing / rebasing!

**Comment by pavertomato** [comment]
https://github.com/GoogleCloudPlatform/healthcare/pull/450

**Pull request closed without merging**
